const ActionTypes = {}

export const GET_CATEGORY_WATCHER = 'GET_CATEGORY_WATCHER'
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS'
export const GET_CATEGORY_FAILURE = 'GET_CATEGORY_FAILURE'

export const GET_ALL_PRODUCTS_WATCHER = 'GET_ALL_PRODUCTS_WATCHER'
export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS'
export const GET_ALL_PRODUCTS_FAILURE = 'GET_ALL_PRODUCTS_FAILURE'

export const GET_PRODUCTS_WATCHER = 'GET_PRODUCTS_WATCHER'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE'

export const DELETE_PRODUCTS_WATCHER = 'DELETE_PRODUCTS_WATCHER'
export const DELETE_PRODUCTS_SUCCESS = 'DELETE_PRODUCTS_SUCCESS'
export const DELETE_PRODUCTS_FAILURE = 'DELETE_PRODUCTS_FAILURE'

export const ADD_PRODUCTS_WATCHER = 'ADD_PRODUCTS_WATCHER'
export const ADD_PRODUCTS_SUCCESS = 'ADD_PRODUCTS_SUCCESS'
export const ADD_PRODUCTS_FAILURE = 'ADD_PRODUCTS_FAILURE'

export default ActionTypes
